server:
  port: 19091

spring:
  main:
    web-application-type: reactive  # Spring 애플리케이션이 리액티브 웹 애플리케이션으로 설정
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:  # Spring Cloud Gateway의 라우팅 설정
        - id: auth-service    # 19092
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
      discovery:
        locator:
          enabled: true  # 서비스 디스커버리를 통해 동적으로 라우트를 생성하도록 설정

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:19090/eureka/
